
version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: auth_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: auth_app
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
